// Page sections, in order. Each metric names its section with `section`. Each section's accent colour
// is set in style.css by its id.
export const SECTIONS = [
  {
    id: 'cp30',
    title: 'Clean Power 2030',
    intro: "The government's three headline measures for its 2030 target. Each chart shows 2020: draw 2021 to 2025.",
  },
  {
    id: 'general',
    title: 'The bigger picture',
    intro: 'Renewables, demand, power station emissions and household bills over a longer period.',
  },
  {
    id: 'forecast',
    title: 'What happens next?',
    intro:
      "Data from NESO's Holistic Transition scenario from the 2025 Future Energy Scenarios. Each chart shows to 2024: draw the forecast.",
  },
];

// One entry per game, in page order. `key` matches a series in data/data.json, and `short` labels it in the score bar.
// The player sees the line up to and including `revealYear`, then draws the rest.
// Values are formatted as `${prefix}${number}${unit}`. `unitLong` replaces `unit` in tooltips and score text,
// which show `dp` decimal places (default 1).
export const METRICS = [
  {
    key: 'clean_generation_share_pct',
    section: 'cp30',
    short: 'Clean generation',
    title: 'Clean share of generation',
    question: "What share of Great Britain's electricity came from nuclear and renewables?",
    revealYear: 2020,
    domain: [0, 100],
    unit: '%',
    target: { value: 95, label: '2030 target: 95%' },
  },
  {
    key: 'clean_demand_share_pct',
    section: 'cp30',
    short: 'Demand met',
    title: 'Demand met by clean power',
    question: "How much of Great Britain's electricity demand could nuclear and renewables cover?",
    revealYear: 2020,
    domain: [0, 100],
    unit: '%',
    target: { value: 100, label: '2030 target: 100%' },
  },
  {
    key: 'emissions_intensity_gco2_kwh',
    section: 'cp30',
    short: 'Carbon intensity',
    title: 'Carbon intensity',
    question: 'How many grams of CO₂ were emitted per kilowatt-hour of electricity?',
    revealYear: 2020,
    domain: [0, 200],
    unit: 'g',
    unitLong: 'g CO₂/kWh',
    // Clean Power 2030 Action Plan ambition ("well below 50g"). This number is not in the DESNZ workbook.
    target: { value: 50, label: '2030 ambition: under 50g' },
  },
  {
    key: 'renewables_share_pct',
    section: 'general',
    short: 'Renewables',
    title: 'Renewable electricity',
    question: 'What share of UK electricity came from renewables?',
    revealYear: 2015,
    domain: [0, 100],
    unit: '%',
  },
  {
    key: 'electricity_demand_twh',
    section: 'general',
    short: 'Demand',
    title: 'Electricity demand',
    question: 'How much electricity did the UK use each year, including what was lost in the grid?',
    revealYear: 2000,
    domain: [0, 450],
    unit: 'TWh',
    unitLong: 'TWh',
  },
  {
    key: 'electricity_supply_emissions_mtco2e',
    section: 'general',
    short: 'Power emissions',
    title: 'Power station emissions',
    question: 'How many million tonnes of greenhouse gases did UK power stations emit each year?',
    revealYear: 2000,
    domain: [0, 250],
    unit: 'Mt',
    unitLong: 'Mt CO₂e',
  },
  {
    key: 'dual_fuel_bill_gbp',
    section: 'general',
    short: 'Energy bills',
    title: 'Household energy bills',
    question: 'What did a typical household pay for gas and electricity each year?',
    revealYear: 2018,
    domain: [0, 2500],
    prefix: '£',
    dp: 0,
  },
  {
    key: 'fes_ht_demand_twh',
    section: 'forecast',
    short: 'Future demand',
    title: 'Future electricity demand',
    question: "How much electricity will Great Britain's system need each year to 2050?",
    revealYear: 2024,
    domain: [0, 800],
    unit: 'TWh',
    unitLong: 'TWh',
  },
  {
    key: 'fes_ht_power_emissions_mtco2e',
    section: 'forecast',
    short: 'Future emissions',
    title: 'Future power emissions',
    question: 'How fast will emissions from electricity generation fall?',
    revealYear: 2024,
    domain: [0, 200],
    unit: 'Mt',
    unitLong: 'Mt CO₂e',
  },
  {
    key: 'fes_ht_electric_cars_m',
    section: 'forecast',
    short: 'Electric cars',
    title: 'Electric cars on the road',
    question: 'How many battery electric cars will be on UK roads?',
    revealYear: 2024,
    domain: [0, 40],
    unit: 'm',
    unitLong: 'million',
  },
];
